### ISSUE TITLE
rubygems version

### ISSUE THREAD

**Issue by AvnerCohen** [Nerian/google-id-token#7]
How about publishing this fork formally in ruby gems?

**Comment by Nerian** [comment]
Well the issue is that I am not one of the maintainers of the original project, so I don't have permission to update the gem in Rubygem. If I were to publish it, it would need to be done under a different gem name. At that point, there is little difference between using the `git: ...` argument and the gem.

The ideal solution would be for the original project owner to either give me permissions in Rubygems or to take care again of this project.

I am not sure what the owners want to do.

Maybe @timbray join the conversation :) What are you plans with https://code.google.com/p/google-id-token/ ?

**Comment by Nerian** [comment]
Looks like Google is maintaining this gem again:

https://github.com/google/google-id-token
